### ISSUE TITLE
Documentation of how to use the directives - meta-Sphinx!

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/sphinxcontrib-opendataservices#2]
https://sphinxcontrib-opendataservices.readthedocs.io/en/latest/

**Comment by Bjwebb** [comment]
Remaining to document:
- [x] javascript supported behaviour of jsoninclude
- [x] JSONSchemaDirective and JSONSchemaFieldsDirective
- [x] Add css to display jsonschema tables nicer
- [x] Add a link from the docs to https://github.com/open-contracting/ocds_sphinx_directives and openreferral directives.

**Comment by robredpath** [comment]
This is live at https://sphinxcontrib-opendataservices.readthedocs.io/en/latest/
